### ISSUE TITLE
Could this code take as input the matrix elements of two-body chiral effective interaction?

### ISSUE THREAD

**Issue by hamad12a** [ragnarstroberg/imsrg#8]
Could this code take as input the matrix elements generated [by this code](https://github.com/Takayuki-Miyagi/NuHamil-public)  ?
If so, how to set the valence space?

**Comment by ragnarstroberg** [comment]
Yes, it can. The ModelSpace class can be initialized with three arguments,
`ModelSpace ms(emax, reference, valence)`
where emax is an integer, reference is a string, like "O16", and valence is a string like "sd-shell". You can also choose "p-shell" or "fp-shell", or various other options, and there is the ability to define a custom valence space. But rather than going into that here, I should just work on producing some proper documentation.

**Comment by ragnarstroberg** [comment]
In any case, this is a question about usage rather than a bug, so I'm closing and suggesting further questions be posted to the "Discussions" tab.

**Comment by hamad12a** [comment]
> In any case, this is a question about usage rather than a bug, so I'm closing and suggesting further questions be posted to the "Discussions" tab.

I'm interested more in larger spaces like sdg valence space where Sn132 is the core and s.p.e are of Sn131, s.h.e are of Sb133. I wonder if it is still implementable.
